version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in build phase
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - ./compile.sh
      - tar cf build.tar.gz build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build.tar.gz
